### ISSUE TITLE
Creation configuration

### ISSUE THREAD

**Issue by TBoileau** [TBoileau/twitch-bot-bundle#3]
```yaml
twitch_bot:
    identity:
        username: ''
        password: ''
    channels:
        - ''
```
